# Generated by Django 3.2.5 on 2021-07-24 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='PersonalBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('feeds', models.ManyToManyField(blank=True, related_name='feeds', to=settings.AUTH_USER_MODEL, verbose_name='Подписки')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики')),
                ('noted', models.ManyToManyField(blank=True, related_name='noted', to='blog.Post', verbose_name='Прочитано')),
                ('posts', models.ManyToManyField(blank=True, related_name='posts', to='blog.Post', verbose_name='Посты')),
            ],
            options={
                'verbose_name': 'Блог пользователя',
                'verbose_name_plural': 'Блоги пользователей',
            },
        ),
    ]
